# Generated by Django 2.0 on 2018-09-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=40)),
                ('useremail', models.CharField(max_length=30)),
                ('userreceipt', models.CharField(default='', max_length=20)),
                ('useraddress', models.CharField(default='', max_length=100)),
                ('usercode', models.CharField(default='', max_length=6)),
                ('userphone', models.CharField(default='', max_length=11)),
            ],
        ),
    ]
